name: database_client
description: Centralized Supabase database client for Zevo.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
